DROP TABLE IF EXISTS password CASCADE;

CREATE TABLE IF NOT EXISTS password
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    login            VARCHAR(250) NOT NULL,
    password         VARCHAR(250) NOT NULL,
    first_name       VARCHAR(250),
    second_name      VARCHAR(250),
    email            VARCHAR(250),
    registration     BOOLEAN NOT NULL,
    data_registration TIMESTAMP NOT NULL
);