DROP TABLE IF EXISTS public.password CASCADE;

CREATE TABLE IF NOT EXISTS password
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    login             VARCHAR(30) NOT NULL,
    password          VARCHAR(30) NOT NULL,
    first_name        VARCHAR(30),
    second_name       VARCHAR(30),
    email             VARCHAR(30),
    registration      VARCHAR(30),
    data_registration VARCHAR(30)
);